version: '3.8'

services:
  # Application service for production
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: acquisitions-app-prod
    ports:
      - '3000:3000'
    env_file:
      - .env.production

    volumes:
      # Only mount logs directory in production
      - ./logs:/app/logs
    networks:
      - acquisitions-prod
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  acquisitions-prod:
    driver: bridge