name: Tests

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        env:
          NODE_ENV: test
          NODE_OPTIONS: --experimental-vm-modules
          DATABASE_URL: ${{ secrets.DATABASE_URL || 'sqlite://test.db' }}
        run: |
          npm test
          TEST_EXIT_CODE=$?
          
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            echo "::error::Tests failed. Please check the test output above for details."
            echo "## :x: Test Results" >> $GITHUB_STEP_SUMMARY
            echo "Tests failed with exit code $TEST_EXIT_CODE" >> $GITHUB_STEP_SUMMARY
            exit $TEST_EXIT_CODE
          else
            echo "## :white_check_mark: Test Results" >> $GITHUB_STEP_SUMMARY
            echo "All tests passed successfully!" >> $GITHUB_STEP_SUMMARY
          fi
          
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: |
            coverage/
            !coverage/tmp
          retention-days: 30
          
      - name: Generate coverage summary
        if: always()
        run: |
          if [ -f "coverage/lcov-report/index.html" ]; then
            echo "## :bar_chart: Coverage Report" >> $GITHUB_STEP_SUMMARY
            echo "Coverage reports have been generated and uploaded as artifacts." >> $GITHUB_STEP_SUMMARY
            echo "Download the artifacts to view detailed coverage information." >> $GITHUB_STEP_SUMMARY
          else
            echo "## :warning: Coverage Report" >> $GITHUB_STEP_SUMMARY  
            echo "No coverage reports were generated." >> $GITHUB_STEP_SUMMARY
          fi